version: '3'

services:
  #web: 
  #  build: ./web
  #  ports: 
  #    - "8080:8080"
  #  depends_on:
  #    - comments

  comments:
    build: ./comments
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  #crawler:
  #  build: ./crawler
  #  ports: 
  #    - "3001:3000"
  #  depends_on:
  #    - mongo

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./mongo/data:/data/db"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root